# Generated by Django 2.1 on 2018-09-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='passwd',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
