# Generated by Django 2.1 on 2018-09-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_ticket', '0003_auto_20180914_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='card_type',
            field=models.CharField(choices=[('EDJ', '二代居民身份证'), ('LSS', '临时身份证'), ('HKB', '户口簿'), ('JRB', '中国人民解放军军人保障卡'), ('JGZ', '军官证'), ('WJJ', '武警警官证'), ('SBZ', '士兵证'), ('JDX', '军队学员证'), ('JDW', '军队文职干部证'), ('JDL', '军队离休干部证'), ('HZ', '护照'), ('GAJ', '港澳居民来往内地通行证'), ('GAT', '中华人民共和国来往港澳通行证'), ('TWJ', '台湾居民来往大陆通行证'), ('DLJ', '大陆居民来往台湾通行证'), ('WJL', '外国人居留证'), ('RJZ', '外国人出入境证'), ('WJG', '外交官证'), ('LSG', '领事馆证'), ('HYZ', '海员证'), ('WGR', '外交部开具的外国人身份证明'), ('DFG', '地方公安机关出入境管理部门开具的护照报失证明'), ('TLG', '铁路公安部门填发的乘坐旅客列车临时身份证明'), ('XSZ', '身高不足1.5m的未成年人学生证')], max_length=3),
        ),
    ]
