# Generated by Django 2.1 on 2018-09-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_ticket', '0004_auto_20180914_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='stations',
            name='station_code',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
