# Generated by Django 2.1 on 2018-09-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_ticket', '0006_seat_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainnumber',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
