# Generated by Django 2.1 on 2018-09-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_ticket', '0007_trainnumber_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainnumber',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
