# Generated by Django 2.1 on 2018-09-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_ticket', '0009_auto_20180919_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriage',
            name='carriage_num',
            field=models.CharField(max_length=20),
        ),
    ]
