# Generated by Django 2.1 on 2018-09-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_ticket', '0010_auto_20180919_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
