# Generated by Django 2.1 on 2018-09-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_ticket', '0011_auto_20180920_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
