# Generated by Django 2.1 on 2018-09-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_ticket', '0013_auto_20180920_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='passstations',
            name='station_num',
            field=models.IntegerField(default=-1),
        ),
    ]
