# Generated by Django 2.1 on 2018-09-20 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_ticket', '0014_passstations_station_num'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='passstations',
            unique_together={('train_num_id', 'station_id', 'seat_type')},
        ),
    ]
