# Generated by Django 2.1 on 2018-09-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_ticket', '0017_auto_20180924_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='changed_train_num_id',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
